# Generated by Django 5.0.4 on 2024-04-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0003_passenger"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passenger",
            old_name="flight",
            new_name="flights",
        ),
    ]
